apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-service-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - devops-platform
  selector:
    matchLabels:
      app: production-ready-aws-platform
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
