apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-platform

resources:
  - namespace.yaml
  - ../../base

images:
  - name: production-ready-aws-platform
    newTag: phase4
